/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminSetupRouteImport } from './routes/admin-setup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDictionaryRouteImport } from './routes/_authenticated/dictionary'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated/learn'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedMyWordsRouteImport } from './routes/_authenticated/my-words'
import { Route as AuthenticatedPlacementTestRouteImport } from './routes/_authenticated/placement-test'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRecordingsRouteImport } from './routes/_authenticated/recordings'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedAdminApprovalsRouteImport } from './routes/_authenticated/admin/approvals'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin/content'
import { Route as AuthenticatedAdminLiveRouteImport } from './routes/_authenticated/admin/live'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin/logs'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminRecordingsRouteImport } from './routes/_authenticated/admin/recordings'
import { Route as AuthenticatedAdminResourcesRouteImport } from './routes/_authenticated/admin/resources'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin/roles'
import { Route as AuthenticatedAdminStudentViewRouteImport } from './routes/_authenticated/admin/student-view'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin/students'
import { Route as AuthenticatedAdminTeachersRouteImport } from './routes/_authenticated/admin/teachers'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminVocabularyRouteImport } from './routes/_authenticated/admin/vocabulary'
import { Route as AuthenticatedCourseCourseIdRouteImport } from './routes/_authenticated/course/$courseId'
import { Route as AuthenticatedLearnIndexRouteImport } from './routes/_authenticated/learn.index'
import { Route as AuthenticatedLearnUnitIdRouteImport } from './routes/_authenticated/learn.$unitId'
import { Route as AuthenticatedPracticeIndexRouteImport } from './routes/_authenticated/practice/index'
import { Route as AuthenticatedPracticeFlashcardsRouteImport } from './routes/_authenticated/practice/flashcards'
import { Route as AuthenticatedPracticeFreeRouteImport } from './routes/_authenticated/practice/free'
import { Route as AuthenticatedPracticePremiumRouteImport } from './routes/_authenticated/practice/premium'
import { Route as AuthenticatedQuizQuizIdRouteImport } from './routes/_authenticated/quiz/$quizId'
import { Route as ApiPublicApplyVocabExamplesRouteImport } from './routes/api/public/apply-vocab-examples'
import { Route as AuthenticatedAdminCoursesIndexRouteImport } from './routes/_authenticated/admin/courses.index'
import { Route as AuthenticatedAdminSectionsIndexRouteImport } from './routes/_authenticated/admin/sections.index'
import { Route as AuthenticatedAdminSectionsSectionIdRouteImport } from './routes/_authenticated/admin/sections.$sectionId'
import { Route as AuthenticatedAdminUnitsUnitIdRouteImport } from './routes/_authenticated/admin/units.$unitId'
import { Route as AuthenticatedAdminCoursesCourseIdContentRouteImport } from './routes/_authenticated/admin/courses.$courseId.content'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin-setup',
  path: '/admin-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDictionaryRoute = AuthenticatedDictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyWordsRoute = AuthenticatedMyWordsRouteImport.update({
  id: '/my-words',
  path: '/my-words',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlacementTestRoute =
  AuthenticatedPlacementTestRouteImport.update({
    id: '/placement-test',
    path: '/placement-test',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecordingsRoute = AuthenticatedRecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminApprovalsRoute =
  AuthenticatedAdminApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLiveRoute = AuthenticatedAdminLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRecordingsRoute =
  AuthenticatedAdminRecordingsRouteImport.update({
    id: '/recordings',
    path: '/recordings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResourcesRoute =
  AuthenticatedAdminResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminStudentViewRoute =
  AuthenticatedAdminStudentViewRouteImport.update({
    id: '/student-view',
    path: '/student-view',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTeachersRoute =
  AuthenticatedAdminTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminVocabularyRoute =
  AuthenticatedAdminVocabularyRouteImport.update({
    id: '/vocabulary',
    path: '/vocabulary',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedCourseCourseIdRoute =
  AuthenticatedCourseCourseIdRouteImport.update({
    id: '/course/$courseId',
    path: '/course/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnIndexRoute = AuthenticatedLearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLearnRoute,
} as any)
const AuthenticatedLearnUnitIdRoute =
  AuthenticatedLearnUnitIdRouteImport.update({
    id: '/$unitId',
    path: '/$unitId',
    getParentRoute: () => AuthenticatedLearnRoute,
  } as any)
const AuthenticatedPracticeIndexRoute =
  AuthenticatedPracticeIndexRouteImport.update({
    id: '/practice/',
    path: '/practice/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticeFlashcardsRoute =
  AuthenticatedPracticeFlashcardsRouteImport.update({
    id: '/practice/flashcards',
    path: '/practice/flashcards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticeFreeRoute =
  AuthenticatedPracticeFreeRouteImport.update({
    id: '/practice/free',
    path: '/practice/free',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticePremiumRoute =
  AuthenticatedPracticePremiumRouteImport.update({
    id: '/practice/premium',
    path: '/practice/premium',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuizQuizIdRoute = AuthenticatedQuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicApplyVocabExamplesRoute =
  ApiPublicApplyVocabExamplesRouteImport.update({
    id: '/api/public/apply-vocab-examples',
    path: '/api/public/apply-vocab-examples',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminCoursesIndexRoute =
  AuthenticatedAdminCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSectionsIndexRoute =
  AuthenticatedAdminSectionsIndexRouteImport.update({
    id: '/sections/',
    path: '/sections/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSectionsSectionIdRoute =
  AuthenticatedAdminSectionsSectionIdRouteImport.update({
    id: '/sections/$sectionId',
    path: '/sections/$sectionId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUnitsUnitIdRoute =
  AuthenticatedAdminUnitsUnitIdRouteImport.update({
    id: '/units/$unitId',
    path: '/units/$unitId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoursesCourseIdContentRoute =
  AuthenticatedAdminCoursesCourseIdContentRouteImport.update({
    id: '/courses/$courseId/content',
    path: '/courses/$courseId/content',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-setup': typeof AdminSetupRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/faq': typeof FaqRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dictionary': typeof AuthenticatedDictionaryRoute
  '/learn': typeof AuthenticatedLearnRouteWithChildren
  '/live': typeof AuthenticatedLiveRoute
  '/my-words': typeof AuthenticatedMyWordsRoute
  '/placement-test': typeof AuthenticatedPlacementTestRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recordings': typeof AuthenticatedRecordingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/live': typeof AuthenticatedAdminLiveRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/recordings': typeof AuthenticatedAdminRecordingsRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/student-view': typeof AuthenticatedAdminStudentViewRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/vocabulary': typeof AuthenticatedAdminVocabularyRoute
  '/course/$courseId': typeof AuthenticatedCourseCourseIdRoute
  '/learn/$unitId': typeof AuthenticatedLearnUnitIdRoute
  '/practice/flashcards': typeof AuthenticatedPracticeFlashcardsRoute
  '/practice/free': typeof AuthenticatedPracticeFreeRoute
  '/practice/premium': typeof AuthenticatedPracticePremiumRoute
  '/quiz/$quizId': typeof AuthenticatedQuizQuizIdRoute
  '/api/public/apply-vocab-examples': typeof ApiPublicApplyVocabExamplesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/learn/': typeof AuthenticatedLearnIndexRoute
  '/practice/': typeof AuthenticatedPracticeIndexRoute
  '/admin/sections/$sectionId': typeof AuthenticatedAdminSectionsSectionIdRoute
  '/admin/units/$unitId': typeof AuthenticatedAdminUnitsUnitIdRoute
  '/admin/courses/': typeof AuthenticatedAdminCoursesIndexRoute
  '/admin/sections/': typeof AuthenticatedAdminSectionsIndexRoute
  '/admin/courses/$courseId/content': typeof AuthenticatedAdminCoursesCourseIdContentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-setup': typeof AdminSetupRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/faq': typeof FaqRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dictionary': typeof AuthenticatedDictionaryRoute
  '/live': typeof AuthenticatedLiveRoute
  '/my-words': typeof AuthenticatedMyWordsRoute
  '/placement-test': typeof AuthenticatedPlacementTestRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recordings': typeof AuthenticatedRecordingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/live': typeof AuthenticatedAdminLiveRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/recordings': typeof AuthenticatedAdminRecordingsRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/student-view': typeof AuthenticatedAdminStudentViewRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/vocabulary': typeof AuthenticatedAdminVocabularyRoute
  '/course/$courseId': typeof AuthenticatedCourseCourseIdRoute
  '/learn/$unitId': typeof AuthenticatedLearnUnitIdRoute
  '/practice/flashcards': typeof AuthenticatedPracticeFlashcardsRoute
  '/practice/free': typeof AuthenticatedPracticeFreeRoute
  '/practice/premium': typeof AuthenticatedPracticePremiumRoute
  '/quiz/$quizId': typeof AuthenticatedQuizQuizIdRoute
  '/api/public/apply-vocab-examples': typeof ApiPublicApplyVocabExamplesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/learn': typeof AuthenticatedLearnIndexRoute
  '/practice': typeof AuthenticatedPracticeIndexRoute
  '/admin/sections/$sectionId': typeof AuthenticatedAdminSectionsSectionIdRoute
  '/admin/units/$unitId': typeof AuthenticatedAdminUnitsUnitIdRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesIndexRoute
  '/admin/sections': typeof AuthenticatedAdminSectionsIndexRoute
  '/admin/courses/$courseId/content': typeof AuthenticatedAdminCoursesCourseIdContentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin-setup': typeof AdminSetupRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/faq': typeof FaqRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dictionary': typeof AuthenticatedDictionaryRoute
  '/_authenticated/learn': typeof AuthenticatedLearnRouteWithChildren
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/my-words': typeof AuthenticatedMyWordsRoute
  '/_authenticated/placement-test': typeof AuthenticatedPlacementTestRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/recordings': typeof AuthenticatedRecordingsRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/live': typeof AuthenticatedAdminLiveRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/recordings': typeof AuthenticatedAdminRecordingsRoute
  '/_authenticated/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/student-view': typeof AuthenticatedAdminStudentViewRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/vocabulary': typeof AuthenticatedAdminVocabularyRoute
  '/_authenticated/course/$courseId': typeof AuthenticatedCourseCourseIdRoute
  '/_authenticated/learn/$unitId': typeof AuthenticatedLearnUnitIdRoute
  '/_authenticated/practice/flashcards': typeof AuthenticatedPracticeFlashcardsRoute
  '/_authenticated/practice/free': typeof AuthenticatedPracticeFreeRoute
  '/_authenticated/practice/premium': typeof AuthenticatedPracticePremiumRoute
  '/_authenticated/quiz/$quizId': typeof AuthenticatedQuizQuizIdRoute
  '/api/public/apply-vocab-examples': typeof ApiPublicApplyVocabExamplesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/learn/': typeof AuthenticatedLearnIndexRoute
  '/_authenticated/practice/': typeof AuthenticatedPracticeIndexRoute
  '/_authenticated/admin/sections/$sectionId': typeof AuthenticatedAdminSectionsSectionIdRoute
  '/_authenticated/admin/units/$unitId': typeof AuthenticatedAdminUnitsUnitIdRoute
  '/_authenticated/admin/courses/': typeof AuthenticatedAdminCoursesIndexRoute
  '/_authenticated/admin/sections/': typeof AuthenticatedAdminSectionsIndexRoute
  '/_authenticated/admin/courses/$courseId/content': typeof AuthenticatedAdminCoursesCourseIdContentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-setup'
    | '/auth'
    | '/contact'
    | '/courses'
    | '/faq'
    | '/admin'
    | '/dashboard'
    | '/dictionary'
    | '/learn'
    | '/live'
    | '/my-words'
    | '/placement-test'
    | '/profile'
    | '/recordings'
    | '/subscription'
    | '/legal/privacy'
    | '/legal/terms'
    | '/admin/analytics'
    | '/admin/approvals'
    | '/admin/content'
    | '/admin/live'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/recordings'
    | '/admin/resources'
    | '/admin/roles'
    | '/admin/student-view'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/admin/vocabulary'
    | '/course/$courseId'
    | '/learn/$unitId'
    | '/practice/flashcards'
    | '/practice/free'
    | '/practice/premium'
    | '/quiz/$quizId'
    | '/api/public/apply-vocab-examples'
    | '/admin/'
    | '/learn/'
    | '/practice/'
    | '/admin/sections/$sectionId'
    | '/admin/units/$unitId'
    | '/admin/courses/'
    | '/admin/sections/'
    | '/admin/courses/$courseId/content'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-setup'
    | '/auth'
    | '/contact'
    | '/courses'
    | '/faq'
    | '/dashboard'
    | '/dictionary'
    | '/live'
    | '/my-words'
    | '/placement-test'
    | '/profile'
    | '/recordings'
    | '/subscription'
    | '/legal/privacy'
    | '/legal/terms'
    | '/admin/analytics'
    | '/admin/approvals'
    | '/admin/content'
    | '/admin/live'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/recordings'
    | '/admin/resources'
    | '/admin/roles'
    | '/admin/student-view'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/admin/vocabulary'
    | '/course/$courseId'
    | '/learn/$unitId'
    | '/practice/flashcards'
    | '/practice/free'
    | '/practice/premium'
    | '/quiz/$quizId'
    | '/api/public/apply-vocab-examples'
    | '/admin'
    | '/learn'
    | '/practice'
    | '/admin/sections/$sectionId'
    | '/admin/units/$unitId'
    | '/admin/courses'
    | '/admin/sections'
    | '/admin/courses/$courseId/content'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-setup'
    | '/auth'
    | '/contact'
    | '/courses'
    | '/faq'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/dictionary'
    | '/_authenticated/learn'
    | '/_authenticated/live'
    | '/_authenticated/my-words'
    | '/_authenticated/placement-test'
    | '/_authenticated/profile'
    | '/_authenticated/recordings'
    | '/_authenticated/subscription'
    | '/legal/privacy'
    | '/legal/terms'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/approvals'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/live'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/recordings'
    | '/_authenticated/admin/resources'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/student-view'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/teachers'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/vocabulary'
    | '/_authenticated/course/$courseId'
    | '/_authenticated/learn/$unitId'
    | '/_authenticated/practice/flashcards'
    | '/_authenticated/practice/free'
    | '/_authenticated/practice/premium'
    | '/_authenticated/quiz/$quizId'
    | '/api/public/apply-vocab-examples'
    | '/_authenticated/admin/'
    | '/_authenticated/learn/'
    | '/_authenticated/practice/'
    | '/_authenticated/admin/sections/$sectionId'
    | '/_authenticated/admin/units/$unitId'
    | '/_authenticated/admin/courses/'
    | '/_authenticated/admin/sections/'
    | '/_authenticated/admin/courses/$courseId/content'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminSetupRoute: typeof AdminSetupRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  FaqRoute: typeof FaqRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ApiPublicApplyVocabExamplesRoute: typeof ApiPublicApplyVocabExamplesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-setup': {
      id: '/admin-setup'
      path: '/admin-setup'
      fullPath: '/admin-setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dictionary': {
      id: '/_authenticated/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof AuthenticatedDictionaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-words': {
      id: '/_authenticated/my-words'
      path: '/my-words'
      fullPath: '/my-words'
      preLoaderRoute: typeof AuthenticatedMyWordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/placement-test': {
      id: '/_authenticated/placement-test'
      path: '/placement-test'
      fullPath: '/placement-test'
      preLoaderRoute: typeof AuthenticatedPlacementTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recordings': {
      id: '/_authenticated/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof AuthenticatedRecordingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/approvals': {
      id: '/_authenticated/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AuthenticatedAdminApprovalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/live': {
      id: '/_authenticated/admin/live'
      path: '/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AuthenticatedAdminLiveRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/recordings': {
      id: '/_authenticated/admin/recordings'
      path: '/recordings'
      fullPath: '/admin/recordings'
      preLoaderRoute: typeof AuthenticatedAdminRecordingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resources': {
      id: '/_authenticated/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AuthenticatedAdminResourcesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/student-view': {
      id: '/_authenticated/admin/student-view'
      path: '/student-view'
      fullPath: '/admin/student-view'
      preLoaderRoute: typeof AuthenticatedAdminStudentViewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/teachers': {
      id: '/_authenticated/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AuthenticatedAdminTeachersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/vocabulary': {
      id: '/_authenticated/admin/vocabulary'
      path: '/vocabulary'
      fullPath: '/admin/vocabulary'
      preLoaderRoute: typeof AuthenticatedAdminVocabularyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/course/$courseId': {
      id: '/_authenticated/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof AuthenticatedCourseCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/': {
      id: '/_authenticated/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof AuthenticatedLearnIndexRouteImport
      parentRoute: typeof AuthenticatedLearnRoute
    }
    '/_authenticated/learn/$unitId': {
      id: '/_authenticated/learn/$unitId'
      path: '/$unitId'
      fullPath: '/learn/$unitId'
      preLoaderRoute: typeof AuthenticatedLearnUnitIdRouteImport
      parentRoute: typeof AuthenticatedLearnRoute
    }
    '/_authenticated/practice/': {
      id: '/_authenticated/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof AuthenticatedPracticeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice/flashcards': {
      id: '/_authenticated/practice/flashcards'
      path: '/practice/flashcards'
      fullPath: '/practice/flashcards'
      preLoaderRoute: typeof AuthenticatedPracticeFlashcardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice/free': {
      id: '/_authenticated/practice/free'
      path: '/practice/free'
      fullPath: '/practice/free'
      preLoaderRoute: typeof AuthenticatedPracticeFreeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice/premium': {
      id: '/_authenticated/practice/premium'
      path: '/practice/premium'
      fullPath: '/practice/premium'
      preLoaderRoute: typeof AuthenticatedPracticePremiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quiz/$quizId': {
      id: '/_authenticated/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof AuthenticatedQuizQuizIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/apply-vocab-examples': {
      id: '/api/public/apply-vocab-examples'
      path: '/api/public/apply-vocab-examples'
      fullPath: '/api/public/apply-vocab-examples'
      preLoaderRoute: typeof ApiPublicApplyVocabExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/courses/': {
      id: '/_authenticated/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sections/': {
      id: '/_authenticated/admin/sections/'
      path: '/sections'
      fullPath: '/admin/sections/'
      preLoaderRoute: typeof AuthenticatedAdminSectionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sections/$sectionId': {
      id: '/_authenticated/admin/sections/$sectionId'
      path: '/sections/$sectionId'
      fullPath: '/admin/sections/$sectionId'
      preLoaderRoute: typeof AuthenticatedAdminSectionsSectionIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/units/$unitId': {
      id: '/_authenticated/admin/units/$unitId'
      path: '/units/$unitId'
      fullPath: '/admin/units/$unitId'
      preLoaderRoute: typeof AuthenticatedAdminUnitsUnitIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses/$courseId/content': {
      id: '/_authenticated/admin/courses/$courseId/content'
      path: '/courses/$courseId/content'
      fullPath: '/admin/courses/$courseId/content'
      preLoaderRoute: typeof AuthenticatedAdminCoursesCourseIdContentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminApprovalsRoute: typeof AuthenticatedAdminApprovalsRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminLiveRoute: typeof AuthenticatedAdminLiveRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminRecordingsRoute: typeof AuthenticatedAdminRecordingsRoute
  AuthenticatedAdminResourcesRoute: typeof AuthenticatedAdminResourcesRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminStudentViewRoute: typeof AuthenticatedAdminStudentViewRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminTeachersRoute: typeof AuthenticatedAdminTeachersRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVocabularyRoute: typeof AuthenticatedAdminVocabularyRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminSectionsSectionIdRoute: typeof AuthenticatedAdminSectionsSectionIdRoute
  AuthenticatedAdminUnitsUnitIdRoute: typeof AuthenticatedAdminUnitsUnitIdRoute
  AuthenticatedAdminCoursesIndexRoute: typeof AuthenticatedAdminCoursesIndexRoute
  AuthenticatedAdminSectionsIndexRoute: typeof AuthenticatedAdminSectionsIndexRoute
  AuthenticatedAdminCoursesCourseIdContentRoute: typeof AuthenticatedAdminCoursesCourseIdContentRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminApprovalsRoute: AuthenticatedAdminApprovalsRoute,
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
  AuthenticatedAdminLiveRoute: AuthenticatedAdminLiveRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminRecordingsRoute: AuthenticatedAdminRecordingsRoute,
  AuthenticatedAdminResourcesRoute: AuthenticatedAdminResourcesRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminStudentViewRoute: AuthenticatedAdminStudentViewRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminTeachersRoute: AuthenticatedAdminTeachersRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVocabularyRoute: AuthenticatedAdminVocabularyRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminSectionsSectionIdRoute:
    AuthenticatedAdminSectionsSectionIdRoute,
  AuthenticatedAdminUnitsUnitIdRoute: AuthenticatedAdminUnitsUnitIdRoute,
  AuthenticatedAdminCoursesIndexRoute: AuthenticatedAdminCoursesIndexRoute,
  AuthenticatedAdminSectionsIndexRoute: AuthenticatedAdminSectionsIndexRoute,
  AuthenticatedAdminCoursesCourseIdContentRoute:
    AuthenticatedAdminCoursesCourseIdContentRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedLearnRouteChildren {
  AuthenticatedLearnUnitIdRoute: typeof AuthenticatedLearnUnitIdRoute
  AuthenticatedLearnIndexRoute: typeof AuthenticatedLearnIndexRoute
}

const AuthenticatedLearnRouteChildren: AuthenticatedLearnRouteChildren = {
  AuthenticatedLearnUnitIdRoute: AuthenticatedLearnUnitIdRoute,
  AuthenticatedLearnIndexRoute: AuthenticatedLearnIndexRoute,
}

const AuthenticatedLearnRouteWithChildren =
  AuthenticatedLearnRoute._addFileChildren(AuthenticatedLearnRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDictionaryRoute: typeof AuthenticatedDictionaryRoute
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRouteWithChildren
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedMyWordsRoute: typeof AuthenticatedMyWordsRoute
  AuthenticatedPlacementTestRoute: typeof AuthenticatedPlacementTestRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRecordingsRoute: typeof AuthenticatedRecordingsRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedCourseCourseIdRoute: typeof AuthenticatedCourseCourseIdRoute
  AuthenticatedPracticeFlashcardsRoute: typeof AuthenticatedPracticeFlashcardsRoute
  AuthenticatedPracticeFreeRoute: typeof AuthenticatedPracticeFreeRoute
  AuthenticatedPracticePremiumRoute: typeof AuthenticatedPracticePremiumRoute
  AuthenticatedQuizQuizIdRoute: typeof AuthenticatedQuizQuizIdRoute
  AuthenticatedPracticeIndexRoute: typeof AuthenticatedPracticeIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDictionaryRoute: AuthenticatedDictionaryRoute,
  AuthenticatedLearnRoute: AuthenticatedLearnRouteWithChildren,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedMyWordsRoute: AuthenticatedMyWordsRoute,
  AuthenticatedPlacementTestRoute: AuthenticatedPlacementTestRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRecordingsRoute: AuthenticatedRecordingsRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedCourseCourseIdRoute: AuthenticatedCourseCourseIdRoute,
  AuthenticatedPracticeFlashcardsRoute: AuthenticatedPracticeFlashcardsRoute,
  AuthenticatedPracticeFreeRoute: AuthenticatedPracticeFreeRoute,
  AuthenticatedPracticePremiumRoute: AuthenticatedPracticePremiumRoute,
  AuthenticatedQuizQuizIdRoute: AuthenticatedQuizQuizIdRoute,
  AuthenticatedPracticeIndexRoute: AuthenticatedPracticeIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminSetupRoute: AdminSetupRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  FaqRoute: FaqRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ApiPublicApplyVocabExamplesRoute: ApiPublicApplyVocabExamplesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
